Importing Code

In [55]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

Loading in Dataset

In [56]:
df = pd.read_csv("data\\pca.csv")
df

x     y     z
0  0.35  1.43  4.23
1  3.71  2.98  1.32
2  2.10  1.29  0.11
3  4.20  0.99  4.67
4  1.63  2.01  0.19

Converting dataframe to Numpy matrix

In [57]:
data = df.to_numpy()
data

array([[0.35, 1.43, 4.23],
       [3.71, 2.98, 1.32],
       [2.1 , 1.29, 0.11],
       [4.2 , 0.99, 4.67],
       [1.63, 2.01, 0.19]])

Creating Standard Scaler

In [58]:
scaler = StandardScaler()
scaler.fit(data)
scaler.mean_

array([2.398, 1.74 , 2.104])

In [66]:
centered = scaler.transform(data)
centered

array([[-1.45977105, -0.44091777,  1.08047427],
       [ 0.93516583,  1.76367108, -0.39844395],
       [-0.21240809, -0.64004192, -1.01338932],
       [ 1.28442746, -1.06673654,  1.30409077],
       [-0.54741414,  0.38402515, -0.97273178]])

Creating Covariance Matrix

In [84]:
cov_mat = np.cov(centered, rowvar=0)
cov_mat

array([[ 1.25      ,  0.21213688,  0.11822325],
       [ 0.21213688,  1.25      , -0.57379687],
       [ 0.11822325, -0.57379687,  1.25      ]])

Finding eigenvectors and eigenvalues and retrieving top k eigenvectors with the largest eigenvalues

In [90]:
eig_vals, eig_vecs = np.linalg.eig(cov_mat)
sort_idx = np.argsort(eig_vals)[::-1]
components = eig_vecs[:, sort_idx]
components = components[:, :2]
components

array([[-0.12318007,  0.93360751],
       [-0.71910442,  0.14967515],
       [ 0.68389729,  0.32553705]])

Projecting data onto lower dimensional space using principal components

In [91]:
transformed = centered @ components
transformed

array([[ 1.23581405, -1.07711324],
       [-1.6559522 ,  1.00734731],
       [-0.20663278, -0.62399993],
       [ 1.50074324,  1.46401703],
       [-0.8739723 , -0.77025116]])